// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/list-workspaces.ts
import { createClient } from "npm:@supabase/supabase-js@^2.99.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
function client(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_workspaces_default = defineTool({
  name: "list_workspaces",
  title: "List workspaces",
  description: "List the Boostmate workspaces (sub-accounts) the signed-in user has access to.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = client(ctx);
    const { data: memberships, error: mErr } = await supabase.from("account_memberships").select("main_account_id, sub_account_id, role").eq("user_id", ctx.getUserId());
    if (mErr) return { content: [{ type: "text", text: mErr.message }], isError: true };
    const mainIds = [...new Set((memberships ?? []).map((m) => m.main_account_id).filter(Boolean))];
    const [{ data: mains }, { data: subs }] = await Promise.all([
      supabase.from("main_accounts").select("id, name, type").in("id", mainIds.length ? mainIds : ["00000000-0000-0000-0000-000000000000"]),
      supabase.from("sub_accounts").select("id, main_account_id, name, is_default").in("main_account_id", mainIds.length ? mainIds : ["00000000-0000-0000-0000-000000000000"])
    ]);
    const result = {
      workspaces: (subs ?? []).map((s) => ({
        id: s.id,
        name: s.name,
        is_default: s.is_default,
        main_account: mains?.find((m) => m.id === s.main_account_id) ?? null
      }))
    };
    return {
      content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
      structuredContent: result
    };
  }
});

// src/lib/mcp/tools/list-funnels.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.99.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^3.25.76";
function client2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_funnels_default = defineTool2({
  name: "list_funnels",
  title: "List funnels",
  description: "List funnels in a Boostmate workspace (sub-account). Use list_workspaces to discover workspace IDs.",
  inputSchema: {
    sub_account_id: z.string().uuid().describe("Boostmate workspace (sub_account) ID.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ sub_account_id }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await client2(ctx).from("funnels").select("id, name, strategy, created_at, updated_at").eq("sub_account_id", sub_account_id).order("updated_at", { ascending: false });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { funnels: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-offers.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.99.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^3.25.76";
function client3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_offers_default = defineTool3({
  name: "list_offers",
  title: "List offers",
  description: "List offers in a Boostmate workspace.",
  inputSchema: {
    sub_account_id: z2.string().uuid().describe("Boostmate workspace (sub_account) ID.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ sub_account_id }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await client3(ctx).from("offers").select("id, name, tier, price, currency, created_at, updated_at").eq("sub_account_id", sub_account_id).order("updated_at", { ascending: false });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { offers: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-business-blueprint.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.99.1";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z3 } from "npm:zod@^3.25.76";
function client4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_business_blueprint_default = defineTool4({
  name: "get_business_blueprint",
  title: "Get business blueprint",
  description: "Return the business blueprint (strategy document) for a Boostmate workspace.",
  inputSchema: {
    sub_account_id: z3.string().uuid().describe("Boostmate workspace (sub_account) ID.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ sub_account_id }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await client4(ctx).from("business_blueprints").select("*").eq("sub_account_id", sub_account_id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { blueprint: data }
    };
  }
});

// src/lib/mcp/tools/list-analytics-entries.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.99.1";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z4 } from "npm:zod@^3.25.76";
function client5(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_analytics_entries_default = defineTool5({
  name: "list_analytics_entries",
  title: "List analytics entries",
  description: "List recent daily analytics entries for a funnel.",
  inputSchema: {
    funnel_id: z4.string().uuid().describe("Funnel ID."),
    limit: z4.number().int().min(1).max(200).describe("Maximum number of entries to return (1-200).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ funnel_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await client5(ctx).from("analytics_entries").select("*").eq("funnel_id", funnel_id).order("date", { ascending: false }).limit(limit);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { entries: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "exqexdgdkvfhmipblnco";
var mcp_default = defineMcp({
  name: "boostmate-mcp",
  title: "Boostmate MCP",
  version: "0.1.0",
  instructions: "Tools for a Boostmate account. Start with list_workspaces to find the workspace (sub_account) ID, then use it to list funnels, offers, analytics entries, or fetch the business blueprint. All tools act as the signed-in user.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_workspaces_default, list_funnels_default, list_offers_default, get_business_blueprint_default, list_analytics_entries_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
